apiVersion: v1
data:
  something: else
  weather: sunny
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-28T09:59:26Z"
  name: my-config
  namespace: default
  resourceVersion: "100400"
  uid: 2c403c0b-d8b2-407e-816f-e0c548916392
