apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: service-lab
  name: api-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend-api
      app: api
      env: test
  template:
    metadata:
      labels:
        type: backend-api
        app: api
        env: test
    spec:
      containers:
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: replicaset-svc
        # readinessProbe:
        #   httpGet:
        #     path: /demo/hello
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     path: /demo/hello
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   failureThreshold: 3
