apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: service-lab
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    targetPort: 8080
  selector:
    type: backend-api
    app: api
    env: test
