---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: service-lab
  name: api-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend-api
      app: api
      env: test
  template:
    metadata:
      labels:
        type: backend-api
        app: api
        env: test
    spec:
      containers:
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: replicaset-svc
        readinessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: service-lab
  name: db-pod-rs
spec:
  selector:
    matchLabels:
      type: backend-db
      app: db
      env: test
  template:
    metadata:
      labels:
        type: backend-db
        app: db
        env: test
    spec:
      containers:
      - name: db
        image: mongo:3.3
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  namespace: service-lab
  name: replicaset-svc
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    type: backend-db
    app: db
    env: test
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: service-lab
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    targetPort: 8080
  selector:
    type: backend-api
    app: api
    env: test
