apiVersion: v1
kind: Pod
metadata:
  namespace: pod-lab
  name: multi-container
  labels:
    app: go-demo
spec:
  containers:
    - name: db
      image: mongo:3.3
      ports:
        - containerPort: 27017
    - name: api-1
      image: vfarcic/go-demo-2
      env:
        - name: DB
          value: localhost
      ports:
        - containerPort: 8080

